### ISSUE TITLE
Integrate the debug package

### ISSUE THREAD

**Issue by aweary** [Aweary/microbe.js#13]
Use [`debug`](https://github.com/visionmedia/debug) for debugging!

**Comment by aweary** [comment]
https://github.com/Aweary/microbe.js/commit/914189362642528e1696dd8aa80d2ff102e4a1e3 has partially implemented this in the `response` methods

**Comment by Aweary** [comment]
Process started in https://github.com/Aweary/microbe.js/commit/914189362642528e1696dd8aa80d2ff102e4a1e3

**Comment by aweary** [comment]
Fully implemented as of now
